Basic Form App Project
oxenprogrammer/basic-form pull request #1
Opened 2021-02-24 18:53 UTC by Paul-Clue

# What We Did:
- We used rails to create a form application using three different methods.
- First, we used the normal HTML form builder element.
- For our second method, we used the rails #form_tag method.
- And last, we used the rails #form_with method.

2021-02-24 21:54 UTC, blackpintz requested changes
# Status: Changes Required 🛑

## Hello team 👋

**Great job on this project.**

### Highlights

- **Linters are properly configured.**
- **Professional README.**
- **Meets all project-specific requirements.**

### Mandatory Requirements

1). **Please remove the `if` statement logic in `views/users/new.html.erb`. You should not have logic (if statements, each loop) in your view files. View-related logic can be encapsulated in View helpers (`app/helpers/*_helper.rb`). See [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from pathwright.**

2). **Check more in the comments below.**

### Optional

- **You can mention in your README file what route one should use for editing a user.**
- **Also mention that the user needs to run `yarn install`. There are dependencies being used in the app because it wouldn't run until I ran this command.**

### Happy coding 🥂.

**You reach me on slack (Rose Wanjohi).**

2021-02-24 21:54 UTC, blackpintz commented on app/controllers/users_controller.rb
> +    # @user = User.new(username: params[:username], email: params[:email], password: params[:password])
Remove this commented code.

2021-02-24 21:54 UTC, blackpintz commented on app/controllers/users_controller.rb
> +    @user = User.new(username: params[:username], email: params[:email], password: params[:password])
You can initialize user with just `@user = User.new`

2021-02-25 01:45 UTC, rindrajosia requested changes
Hello Team :wave:
Status: Changes Required :recycle:

Good job :+1: your project looks nice, it works, no linter issue :smile: but before approving this project let's cover a few details together to make your project better :blush: :arrow_double_down: .

REQUIRED:

- [ ] Readme file: before `rails db:migrate` user must create the database using: rails `db:create`. Please add it.
- [ ] Readme file: To run the project in order to open it in the browser, user must use `rails server` command.
- [ ] Please remove all comments in your model and controller.
- [ ] As my teammate said: You can initialize user with just `@user = User.new`

OPTIONAL:

- [ ] Partial created for user form and reused in edit and new view
- [ ]  Validate the email format by using either a regular expression or a built in URI method.
- [ ] Form view to displays a list of the error messages (with #errors and full_messages usage) 

That's it, you can submit another code review request after making these changes
With all my respect :pray:

Rindra Josia

2021-02-25 02:23 UTC, whiz25 approved these changes
## Approved ✅ 
Well done for making the necessary changes as requested: Readme has been updated, comments removed from the codebase.
Merge this PR and proceed to the next milestone.


### Martin Afani

2021-02-25 04:52 UTC, merged